Cortex/Cortex.Web/Models/Shared/UserDisplayModel.cs
// Cortex - web application for creating and managing neural networks diagrams.
// Copyright (C) 2018  Andrii Zaiev <andrii.zaiev@gmail.com>
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
// 
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.


using System;
using Cortex.Services.Dtos;

namespace Cortex.Web.Models.Shared
{
    public class UserDisplayModel
    {
        public UserDisplayModel(User user)
        {
            Id = user.Id;
            Name = user.Name;
            UserName = user.UserName;
        }

        public Guid Id { get; set; }

        public string Name { get; set; }

        public string UserName { get; set; }
    }
}

Cortex/Cortex.Web/Controllers/MainController.cs
// Cortex - web application for creating and managing neural networks diagrams.
// Copyright (C) 2018  Andrii Zaiev <andrii.zaiev@gmail.com>
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
// 
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Cortex.Web.Controllers
{
    public class MainController : Controller
    {
        [HttpGet("/")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Cortex/Cortex.Web/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cortex.Services.Dtos;
using Cortex.Services.Interfaces;
using Cortex.Web.Models.Users;
using Microsoft.AspNetCore.Mvc;

namespace Cortex.Web.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserService _userService;

        public UsersController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet("/users/{userName}")]
        public async Task<IActionResult> GetUser(string userName)
        {
            User user = await _userService.GetUserAsync(userName);

            if (user == null)
            {
                return NotFound();
            }

            var model = new UserDetailsModel(user);

            return View(model);
        }
    }
}

Cortex/Cortex.Web/Views/Shared/LogInLayout.cshtml
@*
    Cortex - web application for creating and managing neural networks diagrams.
    Copyright (C) 2018  Andrii Zaiev <andrii.zaiev@gmail.com>
    
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.
    
    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*@


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cortex</title>
</head>
<body class="log-in-body">
    <div class="log-in-container">
        <div class="back-link">
            <a asp-controller="Main" asp-action="Index">
                <i class="fa fa-chevron-left fa-10x"></i>
                Back to Home
            </a>
        </div>

        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/dist/bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/dist/bundle.js" asp-append-version="true"></script>
    </environment>
</body>
</html>

Cortex/Cortex.Web/Views/Shared/_Layout.cshtml
@*
    Cortex - web application for creating and managing neural networks diagrams.
    Copyright (C) 2018  Andrii Zaiev <andrii.zaiev@gmail.com>
    
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.
    
    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*@


@{
    if (ViewBag.IsLanding == null)
    {
        ViewBag.IsLanding = false;
    }

    string bodyClass = ViewBag.IsLanding ? "body-landing" : String.Empty;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cortex</title>
</head>
<body class="@bodyClass">
    <nav>
        <ul class="navbar">
            <li>
                <img class="logo" src="/images/logo.svg" alt="Logo" />
            </li>
            <li class="navbar-heading">
                <a href="/" class="fs-1">Cortex</a>
            </li>
            @if (User.Identity.IsAuthenticated)
            {
                <li class="navbar-item">
                    <a id="user-name-label"
                       class="fs-4"
                       asp-controller="Users"
                       asp-action="GetUser"
                       asp-route-userName="@User.Identity.Name.ToLower()">
                        @User.Identity.Name.ToLower()
                    </a>
                </li>
                <li class="navbar-item">
                    <form method="post" asp-controller="Account" asp-action="LogOut">
                        @Html.AntiForgeryToken()
                        <button class="fs-4 button-link">Log out</button>
                    </form>
                </li>
            }
            else
            {
                <li class="navbar-item">
                    <a class="fs-4" asp-controller="Account" asp-action="Register">Register</a>
                </li>
                <li class="navbar-item">
                    <a class="fs-4" asp-controller="Account" asp-action="LogIn">Log in</a>
                </li>
            }
        </ul>
    </nav>

    <div class="main-container">
        @if (User.Identity.IsAuthenticated)
        {
            <ul class="menu">
                <li class="menu-item">
                    <a class="fs-4" asp-controller="Networks" asp-action="CreateNetwork">
                        <i class="fa fa-plus"></i>
                        Create network
                    </a>
                </li>
                <li class="menu-item">
                    <a class="fs-4" asp-controller="Networks" asp-action="GetOwnNetworks">
                        <i class="fa fa-user"></i>
                        Your networks
                    </a>
                </li>
                <li class="menu-item">
                    <a class="fs-4" asp-controller="Networks" asp-action="GetSharedNetworks">
                        <i class="fa fa-users"></i>
                        Shared with you
                    </a>
                </li>
            </ul>
        }
        
        @if (ViewBag.IsLanding)
        {
            <div class="body">
                @RenderBody()
            </div>
        }
        else
        {
            <div class="body">
                @RenderBody()
            </div>
        }
    </div>

    <environment include="Development">
        <script src="~/dist/bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/dist/bundle.js" asp-append-version="true"></script>
    </environment>
</body>
</html>